# Generated by Django 4.2.16 on 2024-09-06 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Издатель')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Изображение обложки')),
                ('description', models.TextField(blank=True, verbose_name='Описание книги')),
                ('file', models.FileField(blank=True, null=True, upload_to='book_files/', verbose_name='Файл книги')),
                ('format', models.CharField(choices=[('PRINT', 'Печатное издание'), ('DIGITAL', 'Электронный носитель')], default='DIGITAL', max_length=10, verbose_name='Формат')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('downloads', models.IntegerField(default=0, verbose_name='Количество загрузок')),
                ('print_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество печатных экземпляров')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='onlineplatform.author')),
            ],
            options={
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True, verbose_name='Приватная полка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineplatform.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Книжные полки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название клуба')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='club_previews/', verbose_name='Превью')),
                ('information', models.TextField(verbose_name='Информация о клубе')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_gallery/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('reader_ticket', models.CharField(blank=True, max_length=25, null=True, verbose_name='№ читательского билета')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='users', to='onlineplatform.category', verbose_name='Любимые категории')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('value', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineplatform.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Обсуждения',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('photo', models.FileField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание новости')),
                ('date', models.DateTimeField(verbose_name='Дата новости')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='onlineplatform.club')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='onlineplatform.bookshelf')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineplatform.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Темы обсуждения',
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='onlineplatform.discussiontopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Сообщения в обсуждениях',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='onlineplatform.galleryimage'),
        ),
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookCrossingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('cover_image', models.ImageField(upload_to='book_crossing_covers/', verbose_name='Фото книги')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Подробное описание')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительная контактная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Объявления бук-кроссинга',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='onlineplatform.category'),
        ),
    ]
