# Generated by Django 4.2.16 on 2024-09-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема/Вопрос')),
                ('contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Телефон')], max_length=10, verbose_name='Метод связи')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Email/Телефон')),
                ('message', models.TextField(verbose_name='Текст обращения')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='onlineplatform.club')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Авторы'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
