# Generated by Django 4.2.16 on 2024-09-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplatform', '0002_feedback_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name_plural': 'Клубы'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Фотогалерея'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
